train_data: KiDS.DR4.x.SDSS.DR14

inference_data: KiDS.DR4.merged

cut:

model: ann

pred_class: True

pred_z: False

specialization:

bands: [u, g, r, i, Z, Y, J, H, Ks]

features_key: all

test: magnitude
