train_data: KiDS.DR4.x.SDSS.DR14

inference_data: KiDS.DR4.cols

model: ann

pred_class: False

pred_z: True

specialization: QSO

cut:

bands: [u, g, r, i, Z, Y, J, H, Ks]

features_key: colors

test_method: magnitude
