train_data: KiDS.DR4.x.SDSS.DR14

inference_data: KiDS.DR4.merged

cut:

model: xgb

pred_class: False

pred_z: True

specialization:

bands: [u, g, r, i, Z, Y, J, H, Ks]

features_key: all

test: magnitude
