train_data: KiDS.DR4.x.SDSS.DR14

inference_data: KiDS.DR4.cols

model: xgb

pred_class: False

pred_z: True

specialization:

cut:

bands: [u, g, r, i, Z, Y, J, H, Ks]

features_key: all

test_method: magnitude
